import { index, pgTable, text, timestamp, uuid } from 'drizzle-orm/pg-core'

/**
 * Example table — replace with your own domain models.
 *
 * Conventions used here:
 * - uuid primary keys generated by Postgres (safe to expose in URLs)
 * - timestamptz for all timestamps, defaults handled by the database
 * - explicit index declarations
 */
export const users = pgTable(
  'users',
  {
    id: uuid('id').primaryKey().defaultRandom(),
    email: text('email').notNull().unique(),
    name: text('name').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [index('users_created_at_idx').on(table.createdAt)],
)

export type User = typeof users.$inferSelect
export type NewUser = typeof users.$inferInsert
